#!/bin/bash

score_i=0
max_i=0

echo "Testes positivos (ficheiros em tests/good/)"

for f in tests/good/*.nx; do
    max_i=`expr $max_i + 1`;
    echo $f
    expected=tests/good/`basename $f .nx`.out
    assembly=tests/good/`basename $f .nx`.s
    
    rm -f out
    dune exec ./natrix.exe $f
    gcc -g -no-pie $assembly
    if ./a.out > out; then
    
	if cmp --quiet out $expected; then
	    score_i=`expr $score_i + 1`;
	else
	    echo "  FALHA : saida errada para $f"
	fi
    else
	echo "  FALHA da interpretação para $f"
    fi
done
echo

echo "Testes negativos (ficheiros em tests/bad/)"

for f in tests/bad/*.nx; do
    max_i=`expr $max_i + 1`;
    echo $f
    rm -f out
    if dune exec -- ./natrix.exe -interpt $f > out 2>&1; then
	echo "  FALHA : a avaliação de $f deveria falhar"
    else
        if grep -q "^error:" out; then
	    score_i=`expr $score_i + 1`;
        else
            echo "  FALHA : deveria mostrar 'error'"
        fi
    fi
done

echo
percent=`expr 100 \* $score_i / $max_i`;
echo "Score: $score_i / $max_i testes, seja $percent%"

rm  -f /tests/good/*.s