#!/bin/bash

# Sets tests directory
cd ./tests

# --- Tests
bash ./run-test Comments
bash ./run-test Variables
bash ./run-test Ifs
bash ./run-test Functions
bash ./run-test Loops
bash ./run-test Output
bash ./run-test Structs

# To run a new category (the name folder in good/bad directory) add:
# bash ./run-test <category>

# Optionally you can select some tests as verbose, simple add the -v option at the end.
# bash ./run-test <category> -v
