#!/bin/bash

bin=../_build/default/crust.exe
score_i=0
number_of_tests=0

echo "Starting the "$1" Tests"

echo " ===> Good Tests"

# Iterate good tests
for f in good/"$1"/*.rs; do
    number_of_tests=`expr $number_of_tests + 1`;
    echo " " $f
    expected=good/"$1"/`basename $f .rs`.out
    assembly=good/"$1"/`basename $f .rs`.s
    
    # Compile file
    $bin $f; gcc -g -no-pie $assembly

    # Compare output
    if ./a.out > out; then
	    if cmp --quiet out $expected; then
	        score_i=`expr $score_i + 1`;
	    else
	        echo "  ERROR: Wrong output at $f"
	fi
    else
	    echo "  ERROR: The interpretation failed at $f"
    fi
done

echo "\n ===> Bad Tests"

for f in bad/"$1"/*.rs; do
    number_of_tests=`expr $number_of_tests + 1`;
    echo " " $f
    
    if $bin $f > out 2>&1; then
    echo "  ERROR : The avaliation of $f didn't failed"
    else
        if grep -q "^error:" out; then
	        score_i=`expr $score_i + 1`;
        else
            echo "  ERROR : No error message found in output"
        fi
    fi
done

percent=`expr 100 \* $score_i / $number_of_tests`
echo "\nScore: $score_i/$number_of_tests tests = $percent%\n"

# Remove tmp files
rm  -f good/"$1"/*.s
rm  -f out
rm  -f a.out
